stages:
  - testing                       # Запуск тестов
  - copy_history_results          # Копирование результата тестов из предыдущего запуска тестов
  - allure-reports                # Генерация отчета
  - deploy                        # Публикация отчета на gitlab pages, в телеграм уведомление

testing:
  stage: testing
  services:
    - selenium/standalone-chrome:latest
  image: python:3.9
  tags:
    - docker
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest -n=1 --alluredir=./allure-results tests
  allow_failure: true
  artifacts:
    when: always
    paths:
      - ./allure-results
    expire_in: 1 day

copy_history_results:
  stage: copy_history_results
  tags:
    - docker
  image: storytel/alpine-bash-curl
  script:
    #- 'curl --location --output artifacts.zip "https://gitlab.com/api/v4/projects/20508574/jobs/artifacts/master/download?job=pages&job_token=$CI_JOB_TOKEN"'
    - unzip artifacts.zip
    - chmod -R 777 public
    - cp -r ./public/history ./allure-results
  allow_failure: true
  artifacts:
    paths:
      - ./allure-results
    expire_in: 1 day
  rules:
    - when: always

allure-reports:
  stage: allure-reports
  tags:
    - docker
  image: frankescobar/allure-docker-service
  script:
     - allure generate -c ./allure-results -o ./allure-reports
  artifacts:
    paths:
      - ./allure-results
      - ./allure-reports
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: deploy
  script:
    - mkdir public
    - mv ./allure-reports/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always

